apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-endpoint
  labels:
    app: go-gin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-gin
  template:
    metadata:
      labels:
        app: go-gin
    spec:
      containers:
        - name: go-gin
          image: hlkittipan/go-endpoint:v1.0.0
          ports:
            - containerPort: 5555
