version: "3.8"
services:
  app:
    image: hlkittipan/go-endpoint:v1.0.16
    restart: on-failure
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    container_name: go-endpoint
    ports:
      - "5555:5555"
    volumes:
      - ./:/app
    environment:
      PORT: "5555"
      GIN_MODE: "release"
#    command: "go run main.go"