version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: go-endpoint
    ports:
      - "5555:5555"
    volumes:
      - ./:/app
    environment:
      PORT: "5555"
    command: "air -c .air.toml"