definitions:
  model.CustomerForUpdate:
    properties:
      email:
        description: Customer E-mail
        example: choo@gmail.com
        maxLength: 255
        type: string
      firstname:
        description: Customer Firstname
        example: Choopong
        maxLength: 255
        type: string
      gender:
        description: Customer Gender
        enum:
        - male
        - female
        example: male
        type: string
      lastname:
        description: Customer Lastname
        example: Choosamer
        maxLength: 255
        type: string
    required:
    - email
    - firstname
    - lastname
    type: object
  model.Response:
    properties:
      code:
        description: Response Code
        type: integer
      status:
        description: Response Status
        type: string
    type: object
info:
  contact:
    email: hlkittipan@gmail.com
    name: API Support
    url: not yet
  description: start
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: not yet
  title: Customers API
  version: "1.0"
paths:
  /customers:
    get:
      consumes:
      - application/json
      description: Get all customer
      operationId: CustomerHandler
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get customer list
      tags:
      - customers
  /customers/:id:
    put:
      consumes:
      - application/json
      description: Update customer by id
      operationId: UpdateCustomer
      parameters:
      - description: id of customer to be updated
        in: path
        name: id
        required: true
        type: integer
      - description: Customer data to be updated
        in: body
        name: Customer
        required: true
        schema:
          $ref: '#/definitions/model.CustomerForUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - ApiKeyAuth: []
      summary: Update Customer
      tags:
      - customers
schemes:
- https
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
